### ISSUE TITLE
Need to make attribution for content in app

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#110]
See https://door43.org/en/obs/front-matter for the attribution content.
In desktop: Add a "License agreement" link in settings to display the content (similar to Android).
In Android: Add the verbiage about the content to the existing license agreement page, or coordinate with desktop to use a common format. Do not display the last paragraph from the content link above.

**Comment by RRohrssen** [comment]
License agreement should be displayed (and agreed to) when they login.

**Comment by RRohrssen** [comment]
Attribution should be displayed in the settings in the Android version.

**Comment by RRohrssen** [comment]
Desktop needs all of these added to the settings page.
1. License agreement
2. Statement of faith
3. Translation guidelines
4. Attribution

**Comment by cdwhitfield73** [comment]
This is complete in Desktop

**Comment by da1nerd** [comment]
> EDIT: this comment may be incorrect.

@cdwhitfield73 I missed this earlier but double check the requirements above. We are not adding a new "Attribution" document but modifying the "License Agreement" document. @PhotoNomad0 please use the license shown below since it is generic enough to be used in all projects not just OBS.

The new License Agreement will be as follows:

# License

This work is made available under a Creative Commons Attribution-ShareAlike 4.0 International License (http://creativecommons.org/licenses/by-sa/4.0)

You are free to:
- **Share** - copy and redistribute the material in any medium or format
- **Adapt** - remix, transform, and build upon the material for any purpose, even commercially.

Under the following conditions:
- **Attribution** - You must attribute the work as follows: "Original work available at http://unfoldingword.org". Attribution statements in derivative works should not in any way suggest that we endorse you or your use of this work.
- **ShareAlike** - If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

Use of trademarks: unfoldingWord is a trademark of Distant Shores Media and may not be included on any derivative works created from this content. Unaltered content from http://unfoldingword.org must include the unfoldingWord logo when distributed to others. But if you alter the content in any way, you must remove the unfoldingWord logo before distributing your work.

```
```

**Comment by da1nerd** [comment]
@cckozie @jag3773 @klappy there's still some confusion on this issue and #109. we need to discuss this some more.

**Comment by da1nerd** [comment]
just noting, I adjusted android to follow how desktop is displaying the attribution as well as the license files.

**Comment by jag3773** [comment]
@neutrinog @cckozie @klappy: The license and attribution are two separate issues.

The generic license file used for new projects should like this: https://git.door43.org/Door43/tq-en/src/master/LICENSE.md (minus the translationQuestions part, of course).  Note that unfoldingWord should **not** be referenced.

The attribution of contributors is in the API as `checking_entity` and `contributors` for each resource.  For attribution purposes, those are the fields that should be used.

**Comment by da1nerd** [comment]
@jag3773 two questions.
1. are we using that same license for Bible and OBS projects (e.g. everything)?
2. the attribution you just described is specific to each resource. Therefore how do you want to display that information since we cannot display that in a single location in the settings.

**Comment by jag3773** [comment]
@neutrinog Licensing of content is per content, not per app.  I don't see a way around this.  There will always be different attribution statements and different licenses per resource.  The licenses will be one of CC BY-SA, Public Domain/CC0, or Free Translate (maybe a couple others).  I don't think this can be implemented accurately until version 3 of the API which explicitly denotes the license of each work.

If you want the data in the settings then you'll need to iterate through the catalog and pull out the relevant license and attribution data for every resource to generate the page.

Right now the content in the API is a mixture of Public Domain and CC BY-SA.

**Comment by klappy** [comment]
Both tagged issues are closed.
