### ISSUE TITLE
Spike: Research adding a tutorial vs simple mode.

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/ts-requirements#186]

**Comment by cdwhitfield73** [comment]
Here's my thoughts.  First, I think we all agree that adding an in-app tutorial will be complex and not possible this sprint or for version 11 on our current time table.  As for a "simple" mode, I would like to suggest two options that might serve the purpose.  The simplest option is to just have all projects default to opening in "review" mode, instead of "read" mode.  Read mode and chunk mode would still always be available if you want to go to them, but for those that don't want to use them, it would be obvious to them what to do from review mode if that were the first mode presented.  This may be enough to ease the confusion that is out there and would not require much code writing time.  The second option would be to have the ability to "toggle" from a simple to a more complex mode.  The complex mode would be what we have now.  The simpler mode would only have the review mode available for projects, hiding read and chunk mode.  If we do that, then instead of calling it "simple" mode and having THAT be something you turn ON, we need to have the simpler mode be the default and then call the more complex mode "Blind draft" mode.  This would be turned on in the settings, right next to the toggle for turning on Gateway Mode.  This would take a little more code writing to implement, but would not be that difficult.  I believe this would give the desired results of making the app a little more user friendly to a newcomer, especially one not trained at a MAST event.
Thoughts? @klappy @cckozie @ChrisJarka

**Comment by jag3773** [comment]
We have discussed defaulting to the "review" mode before.  I think that would be a good route to go.  It definitely doesn't help explain anything though.

At the very least, it might be nice to have pop-ups on each of the 3 modes that gives a 1 phrase or sentence explanation of what it is.  This would only show up on first run, or maybe every time a new project is created until someone clicks "leave me alone" sort of a thing.
